### ISSUE TITLE
TFC.tv addon is not caching

### ISSUE THREAD

**Issue by lsiracer78** [todits-xbmc/todits-xbmc-tv#22]
Hi,
I am not sure if this code is still supported for any updates. I just want to try to report a possible issue with the addon. Recently, after the upgrade on the video quality, I noticed that the app is not caching ahead. Therefore, it will buffer multiple times each episode. I tried the android version of TFC.tv and that application is caching. I am hoping you can update the code to enable cache. Thanks.

-Larry

**Comment by todits-xbmc** [comment]
Thanks Larry. I'll try to investigate more but from the looks of it, this might be related more to Kodi or to the network. The addon only grabs the links to the videos and passes them to Kodi. Kodi is the one that actually plays the video. It's also possible that this might be related to the network or internet connection.

**Comment by lsiracer78** [comment]
Hi,
Thank you for taking the time to look into this. Although it may be
possible that this issue is related to internet connection with some
people, it is not the case with me. My internet speed is consistent,
averaging about 100mbps download and about 10mbps upload. I think that this
should be enough to stream consistent videos if it is being cached. I also
changed the cache settings already in KODI but has not luck. I tried other
addons such as Genesis and it is caching appropriately. This is why I
started checking out the website directly to see if it is TFC's server but
it is not the case either. I really like your addon and your constant
support on this. Any help is greatly appreciated.

Thanks,
Larry

**Comment by todits-xbmc** [comment]
Firstly, I'd like to mention that TFC.tv started streaming encrypted versions only so I guess this does not matter anymore.

Still, I'd like to say sorry if it took a while to get this answered and unfortunately, I couldn't find any answers as to why Kodi behaves differently when it comes to the playback of videos when the Android version of the TFC.tv app works well. I still think this would be related more to Kodi than to the addon in the sense that the addon only grabs the URL of the video for Kodi to play.

It's possible that the issue might be related to the Android release of Kodi you might be using but again, it might not make sense now given the encrypted streams used by TFC.tv.

Closing this.

Thanks.
