### ISSUE TITLE
Update to work with new TFC website layout

### ISSUE THREAD

**Issue by kvcruzat** [todits-xbmc/todits-xbmc-tv#23]
TFC website is updated and the old HTML page parsers no longer work, thus showing no results.

**Comment by ronny1010** [comment]
Yes. same results for me. it seems that they launched the new layout yesterday and its not showing any content on the addon

**Comment by islandtj** [comment]
Please help/update the add on... Was very happy as my wife could stream on TV vs. our computer or mobile phone. Now after the site's renovation, she is unable to stream :(

Looks like there is awareness and discussion here: http://forum.kodi.tv/showthread.php?tid=155870&page=39

**Comment by arcangel919** [comment]
Hi Todits,  big fan here... Hoping that tfc.tv fix will come out soon?  Hopefully you can let us know if or if this will no longer be fix? Thanks a lot.

**Comment by ronny1010** [comment]
CMIK has released an update - working again. 
https://github.com/cmik/cmik.xbmc/raw/57bfa02db645866a4805615b996814505363c861/downloads/plugin.video.tfctv/plugin.video.tfctv-0.0.56-beta1.zip

**Comment by jcollinsjr** [comment]
Hi CMIK,

Thanks for a wonderful add-on!  I've been using it everyday for a year now.

I've installed version 0.0.56 yesterday and had it working all day.  But today, I'm getting an TFC log-in error.  My account is still active with them.  Any ideas on what to do?

Thanks in advance,
jcollinsjr

**Comment by nhkchan** [comment]
cmik's github is here:
https://github.com/cmik/cmik.xbmc

also, there's a new version out today (0.0.57).

**Comment by jcollinsjr** [comment]
Thanks for the reply nhkchan.

I've installed the latest version 0.0.57, after uninstalling 0.0.56.  Unfortunately, I'm getting the same error. I'm not sure what else to do here.

**Comment by nhkchan** [comment]
Can you post the logs?

**Comment by jcollinsjr** [comment]
nhkchan,

For some weird reason, it started working this morning.  I checked it again after work, and its still working.  Thanks for your help!

**Comment by nhkchan** [comment]
It seems that it has something to do with the connectivity to the webservice.  Reading the Kodi thread, CMIK also stated the same thing (timeouts).

glad it worked out.

**Comment by jcollinsjr** [comment]
nhkchan,

I got my first error tonight.  Please check my log file below.  Thank you!

https://paste.ubuntu.com/24797439/

It could possibly be TFC.tv having issues.  I can't seem to do anything on their Android App.

**Comment by nhkchan** [comment]
correct.  cmik confirmed that it's due to latency with their webservice.  I would suggest you use benaranguren's web scraping version.  I have yet to see any errors.

DL: https://github.com/benaranguren/nuodtayo.tv/blob/master/downloads/plugin.video.tfctv/plugin.video.tfctv-0.1.0.zip

Also, I would follow this thread if I were you as well.  that's where the bulk of the discussion is being done.
https://forum.kodi.tv/showthread.php?tid=155870

**Comment by jcollinsjr** [comment]
Cool, I'll start using the new thread.  Thanks for all the help!

**Comment by billrheaume** [comment]
Can someone PLEASE tell me
How to update the app on the fire stick. I see the zip file link but how do I go about installing it?

**Comment by billrheaume** [comment]
How would I install this with the firestick kodi? I don't see how to get the zip file

**Comment by arcangel919** [comment]
Hello guys,  yesterday my tfc.tv was working but im getting the error today after updating to v0. 058 by cmik,  i tried to install benaranguren's zip file but getting error too with some playing for only 2 mins.  Any update guys?  Thanks

Sent from Yahoo Mail on Android 
 
  On Wed, Jun 7, 2017 at 8:32 AM, Ken<notifications@github.com> wrote:   
correct. cmik confirmed that it's due to latency with their webservice. I would suggest you use benaranguren's web scraping version. I have yet to see any errors.

DL: https://github.com/benaranguren/nuodtayo.tv/blob/master/downloads/plugin.video.tfctv/plugin.video.tfctv-0.1.0.zip

Also, I would follow this thread if I were you as well. that's where the bulk of the discussion is being done.
https://forum.kodi.tv/showthread.php?tid=155870

**Comment by nhkchan** [comment]
@arcangel919 ,
below should resolve your 2 min videos issue:

- completely uninstall all tfc addons
- re-install benaranguren's add-on
- after re-installed, go into add-on settings and hit "defaults" (this should clear any existing user/pw if any)
- re-enter user/pw

**Comment by codydude1** [comment]
Nuodtayo has released v1.7, fixes missing movies and has live tv. It is the most perfect version to date.

https://github.com/benaranguren/nuodtayo.tv/tree/master/plugin.video.tfctv

**Comment by jcollinsjr** [comment]
codydude1,

What is the difference between this version and the one that CMIK has out there, 0.0.58 ?

________________________________

**Comment by codydude1** [comment]
jcollinsjr Cmik v.58 is incomplete, it's missing more than half the movies on the addon. v1.7 fixes missing movies.

**Comment by billrheaume** [comment]
Is there a youtube video on how to fix this on the firestick kodi? I am not that computer literate. I will donate money to anyone who makes one for me and I get it working... My wife is driving me mental with this not working.

**Comment by jcollinsjr** [comment]
codydude1 , Thanks for the info!  I'll give this one a try.

________________________________

**Comment by JForce1** [comment]
@codydude1 
Can you please show me the steps how to install nuodtayo on my amazon fire tv.
Much appreciated.

**Comment by codydude1** [comment]
@Jforce1 download this link with es file explorer. Go to kodi, settings, addons, install from zip, internal storage, and downloads. Then find the nuodtayo repo, tfc 1.7 is there. 

If your getting red box error, I recommend you delete your tfc addon, remove the tfc addon files manually on esfile explorer.

https://github.com/benaranguren/nuodtayo.tv/raw/master/downloads/repository.nuodtayo.tv.addons/repository.nuodtayo.tv.addons-0.0.2.zip

**Comment by JForce1** [comment]
@codydude1 
Got it. Its all good now. Thank you so much.
Also extending my big thank you to benaranguren for fixing this addon.

**Comment by kvcruzat** [comment]
CMIK version fixes the issue as well as the banarangren version which is similar to todits that it scrapes from the website

**Comment by billrheaume** [comment]
I have installed them all and still nothing... When someone gets TFC.tv to work please let me know. This is somethingwe pay for I do not understand why they will not put out an app.
